// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/eve-an/estimated/internal/config"
	"github.com/eve-an/estimated/internal/db"
	"github.com/eve-an/estimated/internal/handlers"
	"github.com/eve-an/estimated/internal/httpx"
	"github.com/eve-an/estimated/internal/middleware"
	"github.com/eve-an/estimated/internal/notify"
	"github.com/eve-an/estimated/internal/session"
	"github.com/go-chi/chi/v5"
	middleware2 "github.com/go-chi/chi/v5/middleware"
	"github.com/google/wire"
	"log/slog"
	"net/http"
	"os"
	"time"
)

// Injectors from wire.go:

func InitializeApp(config2 *config.Config) (*httpx.Server, error) {
	server := provideHTTPServer(config2)
	logger := provideLogger()
	sessionNotifier := notify.NewSessionNotifier(config2)
	sessionStore := session.NewSessionStore(sessionNotifier)
	votesHandler := handlers.NewVotesHandler(logger, sessionStore)
	sessionHandler := handlers.NewSessionHandler(logger)
	eventHandler := handlers.NewEventHandler(logger, sessionStore, sessionNotifier)
	application := handlers.NewApplication(votesHandler, sessionHandler, eventHandler)
	middlewareMiddleware := middleware.NewMiddleware(logger, sessionStore)
	handler := provideMux(application, middlewareMiddleware, config2)
	httpxServer := httpx.NewServer(server, handler)
	return httpxServer, nil
}

// wire.go:

var voteEntryStoreSet = wire.NewSet(session.NewSessionStore, wire.Bind(new(db.VoteEntryStore), new(*session.SessionStore)))

var newSessionNotifierStoreSet = wire.NewSet(notify.NewSessionNotifier, wire.Bind(new(notify.Notifier), new(*notify.SessionNotifier)))

func provideLogger() *slog.Logger {
	return slog.New(slog.NewJSONHandler(os.Stdout, nil))
}

func provideHTTPServer(config2 *config.Config) *http.Server {
	return &http.Server{
		Addr: config2.ServerAddress,
	}
}

func provideMux(
	app *handlers.Application,
	mw *middleware.Middleware, config2 *config.Config,
) http.Handler {
	r := chi.NewRouter()
	r.Use(mw.AddSessionCookie)
	r.Use(middleware2.RequestID)
	r.Use(middleware2.RealIP)
	r.Use(mw.Logging)
	r.Use(middleware2.Recoverer)
	r.Use(middleware2.Timeout(time.Duration(config2.ServerTimeout)))

	return app.RegisterAPIRoutes(r)
}
